#!/bin/bash

echo "🌐 Setting up Chat Wrapper Showcase for Real API Usage"
echo ""

# Get API base URL from user
read -p "Enter your API base URL (e.g., http://localhost:3000): " api_url

# Set default if empty
if [ -z "$api_url" ]; then
    api_url="http://localhost:3000"
fi

# Create .env.local file
cat > .env.local << EOF
# Real API Configuration
# Generated by setup-real-api.sh

# Disable mock API to use real endpoints
VITE_USE_MOCK_API=false

# Your API base URL
VITE_API_BASE_URL=$api_url

# API endpoint paths (usually these are correct)
VITE_BRIEF_PLANNER_ENDPOINT=/api/brief-planner
VITE_CONVERSATION_ENDPOINT=/api/conversation
EOF

echo "✅ Created .env.local with real API configuration"
echo ""
echo "📋 Configuration:"
echo "   API Mode: Real API"
echo "   Base URL: $api_url"
echo "   Brief Planner: $api_url/api/brief-planner"
echo ""
echo "🚀 Next steps:"
echo "   1. Make sure your API server is running at $api_url"
echo "   2. Start the showcase: npm run dev"
echo "   3. The showcase header will show '🌐 Real API Mode'"
echo ""
echo "💡 To switch back to mock API:"
echo "   - Change VITE_USE_MOCK_API=true in .env.local"
echo "   - Or delete .env.local to use defaults"
echo ""
echo "📖 For more details, see: ../REAL_API_SETUP.md"